ciudad_homepage:
    path:     /
    defaults: { _controller: CiudadBundle:Default:index }

ciudad_cambiar:
    path: /ciudad/cambiar-a-{ciudad}
    defaults: { _controller: CiudadBundle:Default:cambiar }
    requirements:
        ciudad: .+
