oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

portada:
   path:     /{ciudad}
   defaults: { _controller: OfertaBundle:Default:portada, ciudad: null }

# Ruta simple de la portada
_portada:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect,route: portada, ciudad: '%cupon.ciudad_por_defecto%' }


#usuario:
#    resource: "@UsuarioBundle/Resources/config/routing.yml"
#    prefix:   /

#tienda:
#    resource: "@TiendaBundle/Resources/config/routing.yml"
#    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

pagina_ayuda:
    path: /ayuda
    defaults: { _controller: OfertaBundle1:Default:ayuda }

pagina_estatica:
    path: /sitio/{pagina}
    defaults: { _controller: OfertaBundle:Sitio:estatica }

_pagina_estatica:
    path: /sitio/{pagina}/
    defaults: { _controller: OfertaBundle:Sitio:estatica }

#oferta:
#    path: /{ciudad}/ofertas/{slug}
#    defaults: { _controller: OfertaBundle:Default:oferta }

# Rutas importadas del bundle OfertaBundle
OfertaBundle:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es
    defaults:
        _locale: es
        