tienda_homepage:
    path:     /
    defaults: { _controller: TiendaBundle:Default:index }

tienda_portada:
    path: /{ciudad}/tiendas/{tienda}
    defaults: { _controller: TiendaBundle:Default:portada }